name: Daily project check

on:
  schedule:
    # build runs every weekday at 3AM UTC
    - cron: '0 3 * * 1-5'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: project check
        run: |
          npm i
          npm run build
          npm run test:github
          npm run lint
        env:
          CI: true
